version: "3.9"
services:

  postgres:
    image: postgres:latest
    container_name: transaction_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "transaction"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - R2DBC_URL=r2dbc:postgres://host.docker.internal:5432/transaction
      - R2DBC_USER=postgres
      - R2DBC_PASSWORD=postgres
      - DB_URL=jdbc:postgres://host.docker.internal:5432/transaction
      - DB_USER=postgres
      - DB_PASSWORD=postgres